fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type: annotation
    prefix: /

xmas:
    resource: "@XMasBundle/Controller/XMasController.php"
    type:     annotation
    prefix:   /xmas